### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by mattewid** [LucaSforza/MongoPersistence#15]
**Hello**,

First I want to congratulate you for this project, because it is something very useful;

The suggestion I have is that in the MongoPersistence class you give the option to directly pass the mongodb collection. Without having to pass the connection uri, db name etc...

On a telegram bot that already uses a database connection, Creating a new connection through MongoPersistence might be unnecessary for some people.

But of course, it's good to leave both options integrated. The one that already is and the option to pass only the data collections.

_That's all, I hope this makes sense to you :)_

**Comment by LucaSforza** [comment]
Thank you very much for the suggestion, it is a nice idea and I think I will implement it.

Do you have any ideas on how to implement it or any suggestions that would help me do so?

For now I can't do it because I'm busy at university with deadlines, but as soon as I have time I'll read more suggestions here and implement this functionality

**Comment by mattewid** [comment]
I would love to build. I'll see if I can take some time and help you with that. 🙂
